# Generated by Django 4.2.27 on 2026-01-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_savedjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedJob',
        ),
    ]
