# Generated by Django 4.2.27 on 2026-02-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
