# Generated by Django 4.2.27 on 2026-02-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employerprofile_description_employerprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
